# Generated by Django 3.0.8 on 2020-07-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteachsgm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='img',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='name',
            new_name='Name',
        ),
    ]
